# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_telemetrydestination.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class SecretRef(BaseModel):
    name: constr(max_length=253)
    """
    Name of the Secret, in Modelplane's namespace.
    """


class Spec(BaseModel):
    collector: Literal['Composed', 'External'] | None = 'Composed'
    """
    Whether Modelplane runs the fleet collector. Composed (the default) puts one on the control plane, and every inference cluster exports to it. External composes none, for a platform that already operates one: each inference cluster then exports to the endpoint below directly.
    External gives up the single egress point, one place to change the destination, and the control plane's own series reaching the fleet without a path of their own. Whoever imposed the endpoint has usually provided them already.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    exporters: dict[str, Any]
    """
    The OpenTelemetry collector's exporters block, passed through unread. Modelplane validates that it parses and reports whether the destination accepts writes; it does not model what an exporter is.
    So any exporter the collector provides works, with its TLS, retry and queue settings intact, and a destination keeps working when the collector gains an exporter Modelplane has never heard of.
    """
    extensions: dict[str, Any] | None = None
    """
    The collector's extensions block, passed through unread, for the authenticator an exporter references. Bearer token, basic auth, OIDC and SigV4 all work, because none of them is modelled here.
    """
    secretRef: SecretRef | None = None
    """
    A Secret whose keys Modelplane mounts into the collector as environment variables, so configuration above refers to ${env:TOKEN} and the credential itself never appears in this object or in kubectl output.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class TelemetryDestination(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['TelemetryDestination'] | None = 'TelemetryDestination'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    Where the fleet's telemetry goes. Modelplane composes no collectors until a TelemetryDestination exists: neither tier stores anything, so collecting with nowhere to export would spend GPU-cluster memory on samples nobody reads. Creating one turns collection on everywhere at once.
    There is no per-deployment opt-out. A ModelDeployment's author owns neither the destination nor its bill.
    """
    status: Status | None = None


class TelemetryDestinationList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[TelemetryDestination]
    """
    List of telemetrydestinations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """