# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_metricmapping.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Statement(RootModel[constr(max_length=2048)]):
    root: constr(max_length=2048)


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    passthrough: bool | None = False
    """
    Send this component's own metric names onward as well as the modelplane_* ones they become.
    Off by default, because a series the statements did not rename is one whose meaning Modelplane cannot vouch for across engines, and it costs the same to carry as one that was renamed. On, for reading an engine's raw names during a migration or while debugging that engine.
    A passed-through series is still merged across a deployment's replicas, so it keeps the labels the engine gave it and carries no pod identity.
    """
    statements: list[Statement] | None = Field(None, max_length=128)
    """
    OTTL statements, rendered into the collector's transform processor beside Modelplane's own. Modelplane does not interpret them: what you write here is the collector's own configuration language, documented by OpenTelemetry, and it is the same thing Modelplane writes for vLLM.
    Statements select through their own where clauses, so nothing declares which engine a deployment runs.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    clusters: int | None = None
    """
    How many inference clusters have taken these statements.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class MetricMapping(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['MetricMapping'] | None = 'MetricMapping'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    How one component's metrics become part of the modelplane_* surface. Modelplane renders every MetricMapping into each inference cluster's collector, so a mapping is written once on the control plane and reaches the whole fleet.
    A mapping naming a component Modelplane already provides statements for is additive: its statements run after the built-in ones and its flags apply. That is how passthrough is turned on for an engine that needs no statements of its own.
    """
    status: Status | None = None


class MetricMappingList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[MetricMapping]
    """
    List of metricmappings. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """