# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_modelcache.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class ClusterSelector(BaseModel):
    matchLabels: dict[str, str] | None = None


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Existing(BaseModel):
    claimName: constr(min_length=1)
    """
    Name of a PersistentVolumeClaim in the default namespace of every matched cluster. The same name on each: a cache names one artifact, and a claim that is missing on a cluster leaves that cluster Failed rather than the whole cache.
    """
    readOnly: bool | None = True
    """
    Whether to mount the claim read-only. Defaults to true, since Modelplane did not populate it and an engine writing into someone else's volume is rarely intended.
    """
    subPath: str | None = None
    """
    Directory within the volume holding the weights. Defaults to its root.
    """


class AuthSecret(BaseModel):
    key: str | None = 'HF_TOKEN'
    name: constr(min_length=1)


class HuggingFace(BaseModel):
    authSecret: AuthSecret | None = None
    """
    Optional Secret holding an HF token for gated or private repos. Names a Secret in the ModelCache's own namespace; Modelplane propagates it to each matched cluster for the hydration Job to read.
    """
    repo: constr(min_length=1)
    """
    HuggingFace repository ID.
    """
    revision: str | None = None
    """
    Branch, tag, or commit SHA. Defaults to the repo's default branch.
    """
    sizeGiB: conint(ge=1, le=100000)
    """
    Capacity to allocate for the staged artifact on each matched cluster.
    """


class Oci(BaseModel):
    artifact: Literal['Image', 'ModelArtifact']
    """
    What kind of artifact the reference names, which decides how it mounts. Image is a container image with the weights inside, mounted by Kubernetes as an image volume. ModelArtifact is built to the model spec and read by a CSI driver, because a container runtime will not mount one. Required, and deliberately not defaulted: mounting a model artifact as an image volume succeeds and yields an EMPTY directory, with no error on the pod or the cache, so a wrong guess here is invisible until an engine fails to find weights. Measured on GKE 1.36 with containerd 2.2.6.
    """
    ref: constr(min_length=1)
    """
    A tag or digest. Prefer a digest: a tag is re-resolved on every pod start, so moving it changes what the next pod serves. A private registry's credential is configured on the InferenceCluster by the platform team rather than per namespace.
    """
    subPath: str | None = None
    """
    Directory within the artifact holding the weights. Defaults to its root.
    """


class Spec(BaseModel):
    clusterSelector: ClusterSelector | None = None
    """
    Label selector to pick the InferenceClusters that stage this artifact. If omitted, the cache replicates to every cluster.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    existing: Existing | None = None
    """
    A claim you populated yourself, on every cluster this cache matches. Modelplane stages nothing and provisions nothing: it observes the claim, reports Ready only once it is Bound, and publishes how to mount it. For an air-gapped or regulated fleet whose weights are on disk before Modelplane sees them.
    """
    huggingFace: HuggingFace | None = None
    """
    HuggingFace source. Required when source is HuggingFace.
    """
    oci: Oci | None = None
    """
    OCI source. Required when source is OCI. Nothing is staged onto a volume: the artifact is pulled per node by the cluster itself, so there is no sizeGiB and no hydration Job.
    Modelplane does not read the registry, so it reports a cluster Ready once it has published how to mount the reference, not once the reference is known good. A typo, a missing tag or an unusable credential surfaces at pod start, from the kubelet or the driver, rather than on this resource.
    """
    source: Literal['HuggingFace', 'OCI', 'Existing']
    """
    Which kind of artifact source to stage from. The matching source object (e.g. spec.huggingFace) must be set.
    """


class Mount(BaseModel):
    env: list[dict[str, Any]] | None = Field(None, max_length=8)
    """
    Environment the mount needs to be resolvable, e.g. HF_HUB_CACHE for a HuggingFace cache root.
    """
    volumeMounts: list[dict[str, Any]] | None = Field(None, max_length=4)
    """
    Mounts to add to each engine container.
    """
    volumes: list[dict[str, Any]] | None = Field(None, max_length=4)
    """
    Volumes to add. One of persistentVolumeClaim or image, per source.
    """


class Cluster(BaseModel):
    message: str | None = None
    mount: Mount | None = None
    """
    What a consumer adds to a pod to read this cache on this cluster. A consumer joins on this rather than deriving a claim name, so a second source needs no change in the consumer.
    """
    name: str
    phase: Literal['Pending', 'Hydrating', 'Ready', 'Failed'] | None = None


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Summary(BaseModel):
    ready: str | None = None
    """
    e.g. "2/3"
    """


class Status(BaseModel):
    clusters: list[Cluster] | None = None
    """
    Per-cluster staging status.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    summary: Summary | None = None
    """
    Per-cluster ready / total counts.
    """


class ModelCache(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ModelCache'] | None = 'ModelCache'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class ModelCacheList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ModelCache]
    """
    List of modelcaches. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """